### ISSUE TITLE
Nginx proxy pass does not work

### ISSUE THREAD

**Issue by warcode** [gilbitron/Raneto#10]
A nginx proxy pass such as the one below does not work.
All links go to my base domain instead of domain/site/file*.

    location /site {
            proxy_pass    http://localhost:3000;
    }

**Comment by ryanlelek** [comment]
@warcode @akmalhisyam @johnchristopher @mikegioia @ryanzzff 

Hey all,

Checking in with you to make sure this got solved.
If you're still having issues with Nginx configuration, I can help there.
Otherwise, I'll mark this as closed in about ~1 week if I don't hear back.

**Comment by ryanlelek** [comment]
Please re-open or create a new issue if you still need assistance

**Comment by aissarmurad** [comment]
I have a similar issue... and I fix it updating `gulpfile.js`
in lines:
var dest
gulp.task

**Comment by r0binary** [comment]
I configured everything as described above. It works well for the wiki area, but it seems the paths in the admin area are still not usign the configured base_dir. Can anyone confirm?
