### ISSUE TITLE
[proposal] add label 'up-for-grabs'

### ISSUE THREAD

**Issue by draptik** [gilbitron/Raneto#101]
During our last monthly hack session at work we searched Github for so-called 'up-for-grabs' issues and implemented/fixed some of these issues. See http://up-for-grabs.net/ for a nice list.

Maybe this could attract new contributors by adding this label to selected issues?

Just an idea...

**Comment by ryanlelek** [comment]
The more exposure the better. Thanks for sharing the site. I'll add it in via their GitHub momentarily

**Comment by ryanlelek** [comment]
Pending Pull:
https://github.com/up-for-grabs/up-for-grabs.net/pull/368

**Comment by draptik** [comment]
@ryanlelek Issue can be closed -- pull has been merged:

- https://github.com/up-for-grabs/up-for-grabs.net/pull/368#event-587668805
- https://github.com/up-for-grabs/up-for-grabs.net/commit/9e229d7361bf259c6bdde8f0bd5a1583b43cf55f

**Comment by ryanlelek** [comment]
Done. thanks!
