### ISSUE TITLE
Header/Title Formatting

### ISSUE THREAD

**Issue by mikeack** [gilbitron/Raneto#102]
Is there a way that we can use the actual Jekyll syntax? I want to be able to use the --- instead of /* and */. Also, Atmm (atom.io) recognizes my .md files as "GitHub Markdown," but still tried to emphasize text.

![](http://d.pr/i/19aey+)

**Comment by ryanlelek** [comment]
Yep, the "---" is YAML syntax.  

Please see #18 and add your comments because it looks like we'll be moving to YAML shortly from your request and a few others that can take advantage of using YAML

**Comment by ryanlelek** [comment]
Pending merge of #138
