### ISSUE TITLE
Require Login to View Documentation

### ISSUE THREAD

**Issue by ryanlelek** [gilbitron/Raneto#106]
Setting this to new property to true would require login before any documentation is shown.

Right now there are 2 switches, "authentication" and "allow_editing" which gives 3 scenarios:
1. No web browser editing of documents (allow_editing, false, auth false)
2. Anyone can edit (allow_editing true, auth false)
3. Require login to edit (allow_editing true, auth true)

**Comment by draptik** [comment]
Is this a question? ;)

I don't really see this as a problem anymore.

All 3 options work with https://github.com/gilbitron/Raneto/commit/6433309f7c4a874032b82865514c94da0dd4dcfa

Did I miss something?

**Comment by ryanlelek** [comment]
Your PR was great and complete. I didn't feel right bringing this option up on your PR since it is a separate feature

There is one additional use-case where guests should be denied all access and directed to a login page.
After logging in, they can view the documentation.

**Comment by bschne** [comment]
I actually came across this need today while creating an internal company knowledgebase and implemented a quick & dirty version. 

As far as I'm concerned and if I interpret the current config comments correctly, all content would be restricted to logged-in users if the config is as follows:

  // Set to true to enable the web editor
  allow_editing : false,

  // Set to true to enable HTTP Basic Authentication
  authentication : true,

  // If editing is enabled, set this to true to only authenticate for editing, not for viewing
  authentication_for_edit: false,

OR

  // Set to true to enable the web editor
  allow_editing : true,

  // Set to true to enable HTTP Basic Authentication
  authentication : true,

  // If editing is enabled, set this to true to only authenticate for editing, not for viewing
  authentication_for_edit: false,

I will try to refactor my changes and open a PR as soon as I get to it. Any inputs in the meantime?

**Comment by bschne** [comment]
Created the pull request

**Comment by bschne** [comment]
@ryanlelek thanks for merging my PR, I think this issue can now be closed.
