### ISSUE TITLE
Question: Videos and Users

### ISSUE THREAD

**Issue by c0fe** [gilbitron/Raneto#123]
I have a question on this software, does it support embedding local HTML5 videos and is it possible to require people to login to view the content?

**Comment by ryanlelek** [comment]
@c0fe 
- it is possible to require login for all users. only one account at this time
- We have not embedded HTML5 video yet, but you certainly can with some modification

If you're looking to do tutorial documentation videos, WordPress with this plugin may be a better fit by giving you more features and it's ready to go today
https://wordpress.org/plugins/coursepress/
