### ISSUE TITLE
Editing article removes title and sort

### ISSUE THREAD

**Issue by ramezrafla** [gilbitron/Raneto#128]
When we use the built-in editor and save, we lose the comments at the top. We have to manually add them every time. Any idea where this happens so we can fix it and submit PR?

**Comment by ryanlelek** [comment]
Thanks for submitting @ramezrafla 

What form of comments are you using within the markdown? (I've never used that feature).
"<!---" triple-dash?
If you can provide a sample of content before/after, that would help diagnose

**Comment by ramezrafla** [comment]
Hey @ryanlelek thanks for your attention to this.
We use regular JS comments. I recall this is how we need to add to the sort and description information.

**Comment by ryanlelek** [comment]
@ramezrafla do using the Markdown comments fix your issue?
If so, please mark as resolved.
Otherwise, please provide more information so we can help diagnose

**Comment by WebMatrixware** [comment]
This never got fixed, see #192

**Comment by dinopio** [comment]
This bug is still alive, issue shouldnt be closed.
Using Editor from browser deletes all meta data info from the header of the md file.
