### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by wiggisser** [gilbitron/Raneto#177]
Is there any way to support multiple languages of the knowledgebase within one instance of raneto? So something like `http://docs.myapp.com/en`  and `http://docs.myapp.com/de` displaying only english and german articles respectively. Just creating folders in the content directory doesn't work ...

**Comment by stefannilsson** [comment]
+1 Would love to see this support too!

**Comment by ryanlelek** [comment]
Fixed in #246 by @Orhideous
