### ISSUE TITLE
Raneto is not displayed correctly

### ISSUE THREAD

**Issue by m-schaub** [gilbitron/Raneto#186]
Hello,

I installed Raneto v13 on a Virtual Server with Debian 8.6.0 amd64 Minimal. I installed Node.js via package manager as stated on the Node.js website (https://nodejs.org/en/download/package-manager/). My current version of node is v6.10.0 and of npm it is 3.10.10. I used ` git clone https://github.com/gilbitron/Raneto.git && cd Raneto && npm install && npm start` from Raneto´s GitHub page to install Raneto.

When I am viewing the page from diffrent browsers an different end devices Raneto is not displayed correctly (see imagesy):
![screenshot-2](https://cloud.githubusercontent.com/assets/26569359/24143419/ec7e8c4c-0e29-11e7-9bc2-84817fcf7093.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/26569359/24143415/e9586d30-0e29-11e7-8034-7306e7928cfa.png)

It is working correctly, when I install Raneto on my PC. I tried to run Raneto on Virtual Server with CentOS, with same results. I use https://www.servercow.de/ for hosting. I do not know how to resolve this issue. Maybe someone of you will have an idea :)

I really like Raneto, so I hope I can get it up and running again. Thank you for your work and help.

**Comment by m-schaub** [comment]
I solved the issue! I started Raneto with root privileges. That was causing the issue.

Just run Raneto without root privileges.

**Comment by xhj967** [comment]
i also have this problem,  i am on the win10 system
i attemt to change privileges but no work:(
could you help  me?
