### ISSUE TITLE
Proxy subfolders

### ISSUE THREAD

**Issue by drj-io** [gilbitron/Raneto#189]
We have a main domain http://domain.com/ which is serving up our main document.

We have added a proxy route (AWS ALB) to serve Raneto from https://domain.com/docs/ 

We have changed "base_url" to "/docs", but nothing is served from there.  

Logs show the following:

```
0|server   | GET /docs/ 404 4.870 ms - 2180
0|server   | GET /docs/lib/bootstrap/dist/css/bootstrap.min.css 304 2.712 ms - -
0|server   | GET /docs/lib/highlightjs/styles/solarized_light.css 304 1.680 ms - -
0|server   | GET /docs/styles/raneto.css 304 4.797 ms - -
0|server   | GET /docs/styles/ghostdown.css 304 5.429 ms - -
0|server   | GET /docs/lib/jquery/dist/jquery.min.js 304 8.428 ms - -
0|server   | GET /docs/lib/bootstrap/dist/js/bootstrap.min.js 304 9.149 ms - -
0|server   | GET /docs/lib/highlightjs/highlight.pack.min.js 304 9.042 ms - -
0|server   | GET /docs/lib/fitvids/fitvids.min.js 304 8.891 ms - -
0|server   | GET /docs/lib/masonry-layout/dist/masonry.pkgd.min.js 304 9.202 ms - -
0|server   | GET /docs/scripts/ghostdown.js 304 7.922 ms - -
0|server   | GET /docs/scripts/raneto.js 304 8.475 ms - -
```

We basically want the index of the knowledgebase to be served from "/docs/", not from "/".  Is this possible without modifying the application code?  The load balancer does not have the option to proxy relative paths, from my understanding.

The other alternative is to put another loadbalancer (nginx) on top of this to forward requests and alter the incoming path (from "/docs/*" to "/*"), but this is overkill in my opinion.  We would possibly need to do a subdomain otherwise, which we're not excited about.

Interested in hearing your ideas. Thanks!

**Comment by drj-io** [comment]
I have fixed this by editing `app/index.js` and using the express-urlrewrite middleware: https://github.com/kapouer/express-urlrewrite

Here's what I did:
- `npm install express-urlrewrite`
- add property to the config: `rewrite_prefix: '/docs',`
- bring in the dependency to `app/index.js` -> `var rewrite       = require("express-urlrewrite");`
- use the middleware: `app.use(rewrite(config.rewrite_prefix + '/*','/$1'));`

This takes care of most of the static routes that our users will need. It appears, however, that the login features are now broken, and who knows about the editing capability.

If this is something you guys would like to iterate with me on, I can submit a PR.  Thanks.

**Comment by GrahamDumpleton** [comment]
Issues relates to login page and editing when using base url hopefully addressed by PR #280.

**Comment by ryanlelek** [comment]
Closing due to Graham's PR.
Please reopen if the issue continues.

Thanks Graham!

**Comment by allout58** [comment]
I can't seem to get this to work.... If I set the `base_url` to `/raneto`, the index page loads, but everything else returns HTTP 500 (should be 404? Looking at the logs, it says this page doesn't exist). It looks to be trying to GET `/raneto/` for the index page ✔️ , and tries for `/raneto/styles/raneto.css` for example which it fails to find ❌

**Comment by ryanlelek** [comment]
Yep, I tested it again just now from a fresh clone.
Confirming:
- The index page renders
- The index page has broken asset links (CSS/JS)
- Linked documents/pages do not render any content, instead 404

**Comment by ryanlelek** [comment]
Please see this branch/PR to address your issue and confirm/deny the fix.
https://github.com/gilbitron/Raneto/pull/312
