### ISSUE TITLE
Multi-tenancy.

### ISSUE THREAD

**Issue by hifall** [gilbitron/Raneto#190]
This seems like a nice project!

I wonder how involved it would be to adapt it to work in a multi-tenant environment. That is, keep each tenant's knowledge articles only accessible to that particular tenant. What changes should I make to make it work?

**Comment by ryanlelek** [comment]
A multi-tenant hosting setup is a fine idea and application but is out of scope.
There are many different methods to do this successfully and supporting all of them would be unrealistic. Here are some ideas for further research. Sharing any DevOps scripts you develop would be greatly appreciated and included.

Some Options:
- Standalone VPC for each knowledgebase (VPS is about $5 each per month which may be "worth it")
- Run Nginx and match domains to user/tenant home directory
- Docker + Kubernetes with Nginx Ingress to route traffic based on domain
