### ISSUE TITLE
Saving in Editor Erases Meta Data in Files

### ISSUE THREAD

**Issue by antiwebbite** [gilbitron/Raneto#192]
Hey Guys!

I think I saw this bug logged and closed elsewhere ( #128) but it wasn't clear if it was resolved or not, so it may be a different bug.

After logging in and saving an article, the meta data at the top of files that holds title, description, and sorting gets nuked. No need to actually edit anything.

Repro Video: [Link](http://screencast-o-matic.com/watch/cbfo3oXfCu)

Mac OS X 10.11.6 (15G1217)
Chrome 57.0.2987.133 (64-bit)

**Comment by dinopio** [comment]
This bug is still alive, issue shouldnt be closed.
Using Editor from browser deletes all meta data info from the header of the md file.

**Comment by caique0202** [comment]
That's true indeed or maybe we're still doing something wrong. Any comments/updates?
When I update using the browser I see only two entries like this in the header
--
--

Thanks

**Comment by mralexgray** [comment]
STILL this bug is alive... nuking meta data left and right!  Is this project dead?
