### ISSUE TITLE
404 errors on resources

### ISSUE THREAD

**Issue by WebMatrixware** [gilbitron/Raneto#194]
Let me preface this by saying it is probably just that I do not know what I am doing, but i read all of the similar issues and stackoverflow posts I could find and am still stuck.

Using blank cloud9.io workspace.

Added the following `package.json` file in the root of the project

    {
      "name": "amc-kb",
      "version": "1.0.0",
      "author": "Benjamin Lanning",
      "license": "MIT",
      "repository": {
        "type": "git",
        "url": "git@bitbucket.org:benjaminlanning/amc-kb.git"
      },
      "scripts": {
        "start": "DEBUG=raneto node server.js"
      },
      "dependencies": {
        "debug": "^2.6.4",
        "raneto": "^0.13.0"
      }
    }

Added `config.js` in the root of the project with the following modifications

    theme_dir  : __dirname + '/node_modules/raneto/themes/',
    theme_name : 'default',
    content_dir : __dirname + '/content/',
    public_dir  : __dirname + '/node_modules/raneto/themes/default/public/',

Added `server.js` in the root of the project

    'use strict';
    var debug = require('debug')('raneto');
    var raneto = require('raneto');
    var config = require('./config.js');
    var app = raneto(config);
    var server = app.listen(app.get('port'), function () {
        debug('Express HTTP server listening on port ' + server.address().port);
    });

`npm start` works fine and the express server starts listening, but I get the following  404 errors when i browse to the / of the site.

    raneto Express HTTP server listening on port 8080 +0ms
    GET / 304 69.346 ms - -
    GET /lib/bootstrap/dist/css/bootstrap.min.css 404 8.476 ms - 2221
    GET /lib/highlightjs/styles/solarized_light.css 404 3.363 ms - 2221
    GET /styles/raneto.css 304 3.736 ms - -
    GET /lib/jquery/dist/jquery.min.js 404 5.458 ms - 2221
    GET /lib/bootstrap/dist/js/bootstrap.min.js 404 6.416 ms - 2221
    GET /styles/ghostdown.css 304 5.238 ms - -
    GET /lib/highlightjs/highlight.pack.min.js 404 3.269 ms - 2221
    GET /lib/fitvids/fitvids.min.js 404 5.568 ms - 2221
    GET /lib/masonry-layout/dist/masonry.pkgd.min.js 404 2.455 ms - 2221
    GET /scripts/ghostdown.js 304 2.145 ms - -
    GET /scripts/raneto.js 304 1.261 ms - -
    GET /lib/jquery/dist/jquery.min.js 404 2.923 ms - 2221
    GET /lib/bootstrap/dist/js/bootstrap.min.js 404 3.091 ms - 2221
    GET /lib/highlightjs/highlight.pack.min.js 404 7.152 ms - 2221
    GET /lib/fitvids/fitvids.min.js 404 5.063 ms - 2221
    GET /lib/masonry-layout/dist/masonry.pkgd.min.js 404 3.851 ms - 2221

This feels like i messed up the directory layout somehow (summerized below) but i'm not sure where I went wrong.

````
root
    |
    - content
    - node_modules
        |
        + .bin
        + debug
        + express
        - raneto
            |
            + app
            + bin
            + example
            + logo
            + node_modules
            + test
            + themes
            ...
    .gitignore
    config.js
    package.json
    README.md
    server.js
````

**Comment by WebMatrixware** [comment]
Right, so I'm not sure what produces this issue, but eventually going into the `node_modeuls` folder and running `npm install` for each package in there cleared this up, it is odd that the original install of the packages does not then get their dependencies as well, am I missing a flag i should be setting?

**Comment by TheGabrielRS** [comment]
Did you run `gulp` after the `npm install`? Gulp is responsible for moving the files to the folders where you having 404 error

**Comment by WebMatrixware** [comment]
I did not run gulp afterwards because the documentation says nothing about doing that so I had no idea I should have.
