### ISSUE TITLE
base_url ignored on login page

### ISSUE THREAD

**Issue by yevgenkrylov** [gilbitron/Raneto#200]
I am running raneto 0.13.0 in a docker container with Apache as a reverse proxy on the host machine.

Initially I had issues with loading css stylesheets and js scripts, but after setting correct base_url in the config.default.js file all pages started to render normally , except the login page.

Here I see a lot of 404 errors and in the source code of loaded login page base_url was not prepended to the *.css and *.js files, so login page is not functional.

I checked, {{config.base_url}} is in the login.html template, but for some reason it is ignored.

Please help.

**Comment by yevgenkrylov** [comment]
Ok, found [this](https://www.bountysource.com/issues/43511170-proxy-subfolders) article and after adding
`      config      : config,`
in the "login_page.route.js" file login page loads without any 404 errors, but the login button is not working:
`POST https://example.com/rn-login 404 (Not Found)`

Again, it should be https://example.com**/help/**rn-login - digging further....

**Comment by yevgenkrylov** [comment]
Updated 'themes/default/public/scripts/login.js' with:
`        $.post('./rn-login', $(this).serialize(), function (data) {`
and now can authenticate, but then raneto redirects to the / - again without the base_url prepend

Edit doesn't work as well...

Will probably have to go with a sub-domain option, until it's properly fixed....

**Comment by vitorsomenzi** [comment]
Do you have any update on this question? I have the same issue and can't figure out a solution.

**Comment by r0binary** [comment]
Same issue here. Raneto running behind an nginx reverse proxy. Login won't work as expected using the correct base_url

**Comment by GrahamDumpleton** [comment]
This issue is hopefully addressed by PR #280.

**Comment by ryanlelek** [comment]
Closing due to Graham's PR.
Please reopen if the issue continues.

Thanks Graham!
