### ISSUE TITLE
[bug] browser-based 'Meta information' editor not writing to file correctly

### ISSUE THREAD

**Issue by ber532k** [gilbitron/Raneto#219]
**Edit:** Ups, I seem to have missed issue #192, which addresses exactly this. Sorry for double-posting. I'll just close this issue then.

I guess this is probably connected to changes discussed in issue #18. When using the browser-based interface for editing Meta information, Raneto just writes an empty YAML-Block to the file, also deleting any preexisting Meta information.

Consider the following:

```
---
title: Sample Page
---

Here's some content.
```

If I change the Title via the browser-based Interface the following is written to the corresponding file:

```
---
---
Here's some content.
```

Obviously the data got lost along the way. Also I believe there should be an empty line between the YAML-Block and the content.

**Comment by dinopio** [comment]
This bug is still alive, issue shouldnt be closed.
Using Editor from browser deletes all meta data info from the header of the md file.
