### ISSUE TITLE
PR build_nested_pages() support windows directory separator was reverted. Why?

### ISSUE THREAD

**Issue by denisvmedia** [gilbitron/Raneto#224]
Hi there was a PR #216. And it's now reverted (not present either in dev nor in master). Was it an intentional revert or is it missing by mistake?

**Comment by ryanlelek** [comment]
Not sure what happened via GitHub UI.
I manually restored with a commit that gives you credit:
[95a3b8ac](https://github.com/gilbitron/Raneto/commit/95a3b8ac150556056370c475731d0cc6de441f60)

Thanks for letting me know!
