### ISSUE TITLE
Unable to install Raneto on Ubuntu

### ISSUE THREAD

**Issue by dschumm1** [gilbitron/Raneto#228]
`USER@server:~$` cd Raneto-master/
USER@server:~/Raneto-master$ npm install
loadDep:validator → addNa ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine gulp-shell@0.6.3: wanted: {"node":">=4.8.0 <5.0.0 || >=5.7.0"} (currnpm WARN deprecated jquery.backstretch@2.1.15: Please move to the official package name `jquery-backstretch`
loadDep:validator → netwo ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine bootstrap-rtl@3.3.4: wanted: {"node":"~0.10.1"} (current: {"node":"4npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

> raneto@0.13.0 postinstall /home/user/Raneto-master
> npm run gulp

> raneto@0.13.0 gulp /home/user/Raneto-master
> gulp

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! raneto@0.13.0 gulp: `gulp`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the raneto@0.13.0 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raneto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raneto
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raneto
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Raneto-master/npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! raneto@0.13.0 postinstall: `npm run gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raneto@0.13.0 postinstall script 'npm run gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raneto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs raneto
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls raneto
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Raneto-master/npm-debug.log
USER@server:~/Raneto-master$`

**Comment by ryanlelek** [comment]
Hi there!
Issue appears to be Node's binary is not in your path:
`/usr/bin/env: ‘node’: No such file or directory`

You have NPM installed but for whatever reason Node is not in the path.
Things you may consider to resolve this:
- If you just installed Node in the same terminal session, try logging out and logging back in to refresh the path
- Run `which node` to reveal the location of the `node` binary
- Run `sudo find / -name *node*` to locate files that match "node" and that should reveal the Node binary

Once you have the node binary, Check these links (assuming Bash is your shell)
- https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path
- https://superuser.com/questions/112710/how-do-i-globalize-binaries-in-linux

Closing. Comment/reopen if you have trouble
