### ISSUE TITLE
Ability to add meta tags to the head specifically on search page

### ISSUE THREAD

**Issue by James-Quigley** [gilbitron/Raneto#276]
We have a cryptocurrency spammer hitting our search page with their phone number and website url so that google indexes it highly. 

We'd like to add `<meta name="robots" content="noindex, nofollow">` to our head, but only on our search page. 

Unless I'm missing something, I haven't been able to discover a way to do that.

Any suggestions?

**Comment by TheGabrielRS** [comment]
you could add a value to the config variable in the route search, something like `config.metaRobots = true;` 

and on layout.html template use a `{{#config.metaRobots}}<meta name="robots" content="noindex, nofollow">{{/config.metaRobots}}`

**Comment by James-Quigley** [comment]
I'm unsure of how we could apply this only to the search route? Could pretty simply add a value to our config.js, but that would apply to all pages no?

**Comment by TheGabrielRS** [comment]
if the `config.metaRobots` don't exist in other pages, it's ignored by the render, as hoogan utilizes the same rules of mustache (http://mustache.github.io/mustache.5.html), the `{{#variable}}{{/variable}}` works like a ` if`, so it renders only if the variable exists and is different from `false`

so, you insert the tag you want to be rendered only when the config.metaRobots is defined on the search.js route and parsed as a parameter

**Comment by James-Quigley** [comment]
Oh I see, we would have to edit Raneto source. Would I not need to remove the config.metaRobots on all other pages though since we'd only want this defined on the search page? I can submit a PR for that if desired. Is this a feature that should be in Raneto core?

**Comment by James-Quigley** [comment]
Your solution worked well! Thanks
