### ISSUE TITLE
Request for translations.json doesn't include base_url when latter is set.

### ISSUE THREAD

**Issue by GrahamDumpleton** [gilbitron/Raneto#279]
When the ``base_url`` is set to a non empty value, the front end isn't including the ``base_url`` in the request made for ``translations.json``.  This is related to similar problems in #189 and #200.

**Comment by GrahamDumpleton** [comment]
This issue is hopefully addressed by PR #280.

**Comment by ryanlelek** [comment]
Closing due to Graham's PR.
Please reopen if the issue continues.

Thanks Graham!
