### ISSUE TITLE
Menu not being displayed after move to bootstrap 4.

### ISSUE THREAD

**Issue by GrahamDumpleton** [gilbitron/Raneto#286]
Back when using bootstrap 3, in ``page.html`` it used:

```
  <div class="col-sm-3 hidden-xs">
    <ul class="menu">
```

This meant that on small width displays, the menu of articles/categories was hidden.

Now that using bootstrap 4, this was changed to:

```
  <div class="col-sm-3 d-none">
    <ul class="menu">
```

In the situation I am using Raneto, which is actually embedded in an iframe, the menu is now never showing, and when you increase width of browser window, you end up with blank area to right of content.

![image](https://user-images.githubusercontent.com/507637/51435664-82846200-1cd0-11e9-98d6-4790a39e9e38.png)

I am find that I need to change it to:

```
  <div class="d-sm-block d-none">
    <ul class="menu">
```

This change appears to match recommended change for when going from bootstrap 3 to 4 in:

* https://stackoverflow.com/a/19660155/128141

I have the change in my own custom theme at present so you can evaluate suggestion first.

**Comment by GrahamDumpleton** [comment]
Whoops, meant:

```
  <div class="d-sm-block d-none">
    <ul class="menu">
```

Fixed original report, but in email may show as wrong.

**Comment by GrahamDumpleton** [comment]
Seems that change is a start, but not complete solution, as when you make it wide enough still, the content doesn't always expand right, so still end up with space on right side.

![image](https://user-images.githubusercontent.com/507637/51435841-61724000-1cd5-11e9-9227-cbadf0aaff7c.png)

**Comment by GrahamDumpleton** [comment]
I found this works best:

```
  <div class="col-sm-3 d-sm-block d-none">
    <ul class="menu">
```

By adding ``col-sm-3`` into the ``div`` for the menu and with the content itself being ``col-sm-9``, the result is that the content column will fill out to the maximum width it can and don't get space on the right side.

**Comment by ardydavari** [comment]
Graham's comment fixed my error with the menu bar not showing up. I think this edit should be committed to main.

**Comment by Synt3x** [comment]
Hello @GrahamDumpleton 

I'm having the same problem as you pointed out with the side menu. Have you talked with the developers about this problem or tried send them a pull request with a fix for this problem?

/Synt3x

**Comment by GrahamDumpleton** [comment]
I stopped using it some time back.

**Comment by ryanlelek** [comment]
Closing, please see #315 
Sorry we didn't get to this sooner
