### ISSUE TITLE
Grunt - Gulp for automation

### ISSUE THREAD

**Issue by izifortune** [gilbitron/Raneto#29]
I will be very interested in adding one of those to raneto. I got experience mostly with Grunt. Let me know if this could be interesting for you

**Comment by sbussard** [comment]
This PR adds gulp if you're interested
https://github.com/gilbitron/Raneto/pull/64

**Comment by ryanlelek** [comment]
@izifortune Yes, Gulp was added by @sbussard 
Tagging because you might want to check out.

Closing issue.
