### ISSUE TITLE
Pages won't load if I include an ignore file

### ISSUE THREAD

**Issue by philipstratford** [gilbitron/Raneto#308]
Even though it's not documented, I can see in `contents.js` that the file processor is supposed to ignore directories which contain an `ignore` file. That's exactly what I'm looking for.

However, when I create a file named `ignore` (with no extension) in a subfolder of my `content` folder, Raneto seems to fail altogether - pages no longer load. Renaming the file to anything else, like `ignore123` allows pages to load again.

My knowledge of node.js is very limited but I've managed to run Raneto in debug and when the issue described above occurs (i.e. when there's an `ignore` file in a directory) the console shows the error _**The "path" argument must be of type string. Received type undefined**_, referencing line 39 of `contents.js`.

**Comment by ryanlelek** [comment]
Thank you! Closing
