### ISSUE TITLE
The video I inserted. Mp4 file cannot play in safari

### ISSUE THREAD

**Issue by ilovebamboo** [gilbitron/Raneto#319]
我插入的视频.mp4文件 无法在safari播放
The video I inserted. Mp4 file cannot play in safari
如果我不加人www.abc.com:3000/abc.mp4,无法播放，Chrome没有问题。
If I don't add www.abc.com:3000/abc.mp4, cannot play, Chrome no problem.
www.abc.com/abc.mp4, safari can not play video.
必须包括端口3000才行。
https://i.loli.net/2020/03/22/gdMA2qPcI4jFsJo.png

**Comment by ryanlelek** [comment]
Playing MP4 videos natively is more of a browser issue (Safari, Chrome, Firefox).
You can work around this using a JavaScript video player.

I just tested this page in Chrome... video loaded
And it did not load in Safari. 
https://www.learningcontainer.com/mp4-sample-video-files-download/

So you are right, but this is up to the browsers to implement on their side

Some JavaScript frameworks for playing video you can use:
- https://videojs.com/
- https://blog.bitsrc.io/5-open-source-html5-video-players-for-2018-38fa85932afb
