### ISSUE TITLE
Loading failed for http://localhost:3000/lib/fitvids/fitvids.min.js

### ISSUE THREAD

**Issue by jrichardsz** [gilbitron/Raneto#329]
fitvids.min.js is not loaded 

![https://i.ibb.co/pQMWWPy/Screenshot-from-2020-11-10-14-59-43.png](https://i.ibb.co/pQMWWPy/Screenshot-from-2020-11-10-14-59-43.png)

# Fix

add dist in this line of [layout.html](https://github.com/gilbitron/Raneto/blob/master/themes/default/templates/layout.html#L140)

from 

    <script src="{{config.base_url}}/lib/fitvids/fitvids.min.js"></script>

to

    <script src="{{config.base_url}}/lib/fitvids/dist/fitvids.min.js"></script>

I can perform a pull request if you are able to accept it.

**Comment by ryanlelek** [comment]
Closing this issue, PR merged
