### ISSUE TITLE
Install SSL (HTTPS) Certificate on Raneto

### ISSUE THREAD

**Issue by DoctorRiceYouSee** [gilbitron/Raneto#336]
Right now, I got Raneto to run on Apache2 via reverse proxy. I'd like to make it into a HTTPS website. How do I go about installing the SSL certificates on Raneto/Apache2 so I can get it to be HTTPS? Thanks in advance!

**Comment by chrisjsimpson** [comment]
Read about https://certbot.eff.org/

**Comment by ryanlelek** [comment]
Yes, as chrisjsimpson mentions, once you have Raneto working on Apache over HTTP-only, then adding HTTPS is entirely in Apache-land.

Certbot acts as a "free" provider of TLS/SSL certificates that expire relatively quickly (2-3 months). There's also an option of year-long certificates if you buy from one of the many TLS/SSL certificate vendors (Verisign, Digicert, etc) and that can range anywhere from $20-1,000 per year.

There is little technically different between the free Certbot certificates (which can auto-renew if set up) and the multi-thousand certificates. Typically, the price provides a certain brand or features that help "build trust" with customers and site visitors.

Certbot will work just fine for use on Raneto documentation and there are plenty of tutorials on how to add it to Apache as Certbot has grown rapidly in usage

**Comment by nickkostov** [comment]
You can get SSL for 5 bucks from https://www.ssls.com/?gclid=CjwKCAjw9MuCBhBUEiwAbDZ-7kF5lrMqSiYg1Pnp8kk6JWavk8ZC-FAaJUcmrw4UJYxGj2sye_5xDxoCYXoQAvD_BwE there are even cheaper. An valid GoDaddy certificate was issued for 1 cent from them for their use they resell that with 2800% increase.

**Comment by ryanlelek** [comment]
@chrisjsimpson and @nickkostov are correct

Functionally, the EFF Certbot and commercial TLS/SSL certs are the same
- CertBot requires a little bit more effort, renewing every ~3 months or so
- Commercial certificates will usually last 1 year. Even if you buy an extended cert for ~5 years, now most require a new certificate to be generated annually, so a "5-year" certificate will get you 5x 1-year certificates. Something to be aware of

Closing
