### ISSUE TITLE
#312 PR broke my setup

### ISSUE THREAD

**Issue by Vorsku** [gilbitron/Raneto#338]
Hi,

pull request #312 seems to have broken my setup.

I previously had base_url set to https://docs.domain.com which worked prior to the release of 0.16.5

Now when I try to use 0.16.5 I get 'Cannot GET /' in the browser. Changing base_url to blank fixes the issue, however it means I can no longer use %base_url% in documentation to reference the base URL

Thanks

**Comment by ryanlelek** [comment]
Thank you for letting us know and so quickly.
I'll look into this in a bit.

To clarify, you had `config.base_url` set to `https://docs.domain.com` and in the documentation files (.md extension), they are not resolving `%base_url%`. You must set `config.base_url` to `''` to get it somewhat working again.

**Comment by Vorsku** [comment]
Hi,

Thanks for the quick reply!

To clarify, I am running it in the LSIO docker container - when the container starts and I browse to ```https://docs.domain.com``` it doesn't load the normal Raneto index page, it just brings up the error "Cannot Get /"

![IMG_20201226_134717.jpg](https://user-images.githubusercontent.com/14562134/103154834-48604c80-4792-11eb-90de-6092e1e8e64a.jpg)

To fix this, in the ```config.default.js``` file I had to do:
![Screenshot_2020-12-26-15-56-01-721_com.sonelli.juicessh~2.jpg](https://user-images.githubusercontent.com/14562134/103155203-3f24af00-4795-11eb-9a6b-af495f8d2ec5.jpg)

I believe the fact that I can no longer use %base_url% in files is just because it's now blank.

Thanks,
Josh

**Comment by ryanlelek** [comment]
Ok, here's what I found:
- 1) I have confirmed the bug. "" works and "[any base uri]" gives the "Cannot GET /" error
- 2) Putting `nowrap: true,` under the `base_url` parameter solves the issue
- 3) Warning: this will load ALL assets through that Base URL, including site assets. This goes beyond Markdown files `%base_url%`

Please add the `nowrap: true,` to your config and let me know if that resolves. If it does, I'll add the `nowrap` parameter to the example and republish.

**Comment by Vorsku** [comment]
Yep this now works! Thanks @ryanlelek 

![IMG_20201226_194951.jpg](https://user-images.githubusercontent.com/14562134/103158246-96d21300-47b3-11eb-8bca-2599041b4129.jpg)
