### ISSUE TITLE
Export doc to pdf

### ISSUE THREAD

**Issue by DarianAnjuhal** [gilbitron/Raneto#339]
Hi,

I try to export the whole doc to a pdf (or a single html page that can be converted to pdf).

Are there any features or workarounds or code bases already?
Or is it possible to show a clean single html page which can be used as step in between (ranento -> single html page -> pdf)?

Would be nice if you can point me to a correct/possible direction.

Bye Darian

**Comment by ryanlelek** [comment]
Please tell us more about what you're looking to accomplish.
- Are you looking to print the entire documentation base?
- Is this for you and your team or for public users of Raneto?

Some options:
- "Print" to PDF with many popular web browsers. If there are design elements that show up, we can tweak the CSS styles to make it just the content.
- You can print all the Markdown files with a markdown viewer or something like [this Chrome extension](https://chrome.google.com/webstore/detail/github-markdown-printer/fehpdlpmcegfpbkgcnaleindodeegapk)

**Comment by DarianAnjuhal** [comment]
Hi and thank you for your answer.

Its for public users for raneto.
I forked raneto and added the pdf support already.
Because lack of time the project is currently freezed.

But maybe your "Print to PDF" idea could solve our issue as well. Thanks for the hint.

Thx Darian

**Comment by ryanlelek** [comment]
Ok, glad to hear. Closing.
Please open again if your situation changes or you'd like to contribute your PDF export
