### ISSUE TITLE
Why sync ?

### ISSUE THREAD

**Issue by Subash** [gilbitron/Raneto#39]
After looking at the code of raneto-core I can see that you are using sync io. Isn't that slow and opposite of the node practices.

**Comment by ryanlelek** [comment]
Hi @Subash,

I'm not very familiar with the Syncio module, but according to its [NPM Repository Page](https://www.npmjs.com/package/syncio), it seems to just make code appear synchronous with asynchronous code under the hood. If that's right, it shouldn't be blocking Node's event loop.

Additionally, Raneto's target audience is for lower-traffic sites where performance is less of an issue. Are you experiencing any slow-downs with your Raneto installation?

Closing this issue for now, but if you have additional questions, please reopen the issue or create a new one and I'll give it a look.
