### ISSUE TITLE
Markdown Extra

### ISSUE THREAD

**Issue by jbrooksuk** [gilbitron/Raneto#40]
Would it be possible to make use of Markdown Extra? It gives some benefits over standard Markdown such as being able to add classes to images etc.

**Comment by ryanlelek** [comment]
Marking as "wontfix" and closing because:
- Markdown is the dominant and popular format
- the JS-based extra parser that @vyp found has not been commited on since 2014

If you'd like to add Markdown Extra, please submit a PR

**Comment by vyp** [comment]
markdown extra is probably dead or going to die soon anyway. use commonmark.
