### ISSUE TITLE
Can't search in Chinese.

### ISSUE THREAD

**Issue by shuhankuang** [gilbitron/Raneto#41]
I find that it can't work with Chinese. :(

**Comment by ryanlelek** [comment]
Chinese search support was mentioned in another issue, and I'll summarize it here.

@vyp said:
> For Chinese searching, you will probably have to modify raneto to add support for lunr-languages: olivernn/lunr.js#91 (comment). But as you can see in that link, lunr-languages does not yet support Chinese.
>
> Another potential option would be to try and replace the lunr that Raneto uses with https://github.com/codepiano/lunr.js, which seems like a Chinese version of lunr.js (found with the comment just below the previously linked comment). I haven't used this though, so I'm not sure if this only support Chinese, or supports both English and Chinese.

@codepiano replied:
>My fork of lunr supports both English and Chinese.I use it to replace the original lunr repo in gitbook dependencies, and it works well.
> ...
> I'll test whether it works well in Raneto when I have time. Raneto is a nice tool.

Looping you all in via mention so we can restart this and get a solution.
@luxuryzhou, @shuhankuang, @nykma, @OneManOpsTeam, @in-in

**Comment by codepiano** [comment]
Gitbook use lunr.js to build search index from original markdown files, store the index in a file,and load this file in web page.
If Raneto also uses lunr.js this way,maybe my fork version will also work.

**Comment by ZhangTongLe** [comment]
@codepiano 我按照您的方案配置了lunr.js 和Raneto，nodejieba 也安装好了，但是搜索中文的时候，还是不能搜索中文,不造啥原因~，大神能帮忙集成一下，十分感谢~！

**Comment by ZhangTongLe** [comment]
@codepiano     @ryanlelek       Thank OF provide such a good tool, replaced by the support of the Chinese lunr.js codepiano has successfully support Chinese search

**Comment by ryanlelek** [comment]
Fixed in #246 by @Orhideous
