### ISSUE TITLE
Any plans to allow editing/creating pages from the browser?

### ISSUE THREAD

**Issue by sg-s** [gilbitron/Raneto#43]
This is really nice, but I think it would be much more powerful if there was a way to create/edit pages from the editor. Any plans for this?

**Comment by vyp** [comment]
Just fyi, the author has actually addressed this: https://github.com/gilbitron/Raneto/issues/32#issuecomment-51338747. However, that was some time ago.

**Comment by sg-s** [comment]
thanks, though that's disappointing.
