### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by SystemParadox** [gilbitron/Raneto#46]
Firstly, just want to say how much I love this project, thanks for your great work :)

I see that raneto is published to npm. It actually runs very well like this. Great job exposing app and config!

However, it appears that it is not possible to configure the content directory, which makes it impractical to use it this way at the moment.

Is there any chance this could be fixed?

Thanks very much!

**Comment by SystemParadox** [comment]
So 5 seconds after writing this I noticed that the github version does allow this.

It seems that npm is rather behind. Could we get the updated version(s) published?

Thanks.

**Comment by ryanlelek** [comment]
Hi @SystemParadox,

I just checked npm with `npm show raneto versions` and see v0.2.0 and v0.6.0 (latest) are published.
Does the latest v0.6.0 version published solve what you were looking to solve?

I'll publish future updates to NPM as well, so you'll have the latest version.

**Comment by SystemParadox** [comment]
Yes 0.6.0 is there now. I note however that raneto-core is out of date (npm 0.2.0, github 0.3.0).

**Comment by ryanlelek** [comment]
@SystemParadox, I see. I'll work with @gilbitron to get the new releases of "raneto" and "raneto-core" published for you and others.

See also #52 for the usage we're moving towards so NPM module usage is easier and can co-exist with your documentation content. Any feedback you have, please send along (check the example/ directory on v0.7.1)

**Comment by gilbitron** [comment]
"raneto-core" is managed by my on NPM. I'm not sure why it doesn't gave the latest version (0.3.0) but I'll look into that. The "raneto" package was actually registered by someone else on NPM, so I'm not sure how I can take that over to manage it.

**Comment by SystemParadox** [comment]
A useful guide to this is at: https://www.npmjs.com/policies/disputes

**Comment by ryanlelek** [comment]
@SystemParadox 

gilbitron mentioned he published the latest v0.7.1 release to NPM.
More improvements to come, but v0.7.1 should have the base for what you're looking to accomplish.
Could you see if this fixes the issue for your use-case?

**Comment by ryanlelek** [comment]
@SystemParadox
Checking in with you :)
Will mark this closed in a week if I don't hear back

Ryan

**Comment by SystemParadox** [comment]
Thanks. I haven't been able to check but I'm sure it'll be sorted so feel
free to close. Thanks.
