### ISSUE TITLE
Start from different project without requiring install

### ISSUE THREAD

**Issue by santiagoaguiar** [gilbitron/Raneto#52]
I would love to be able to run raneto by creating my content on my own git repo, configure my own  `package.json`, do a `npm install --save raneto` and then add my own entry point similar to what you have on `bin\www`:

However, I would need to pass to `app.js` a config file to use (which I want stored on my own repo), and also be able to specify a static files configuration for express that is evaluated before ranetos own public/ folder.

For example, if `app.js` was something like: 

    var express = require('express'),
        path = require('path'),
    ...
    module.exports = function(options) {
        options = options || {}
       // Setup views
      ...
      // Setup Express
     app.use(favicon(options.favicon || (__dirname +'/public/favicon.ico')));
     ...
     if (options.static) {
         app.use(express.static(options.static));
     }

     app.use(express.static(path.join(__dirname, 'public')));
     ...
     // Setup config
     extend(raneto.config, config, options.config || {});

Then in my own entry point could just do:

    ...
    var app = require('../app')({ config: require("./config"), static: "override" });
    app.set('port', process.env.PORT || 3000);
    ...

To provide an override folder for raneto resources, and a custom config.

What do you guys think? Does it make sense? Should I submit a PR? Or is there other way to do this?

The main goal are:
* Keep in my repo only what I authored, and no raneto code.
* Let people get my repo and just do a standard `npm install; npm start` to start up the site.

**Comment by ryanlelek** [comment]
Hi @santiagoaguiar,

Yes, I agree that the published NPM module should perform this way as it's in line with how other modules perform, where content is not stored in the module itself.

I'll look into this, and it's one of the top priorities for me as well.

**Comment by ryanlelek** [comment]
@santiagoaguiar,

In v0.7.1, I've started making the move to this structure.
It's not quite ready and not available via NPM (yet), but you can checkout the new example/ directory and see if it's in line with what you're after and we can continue the discussion on where to take it next.

**Comment by ryanlelek** [comment]
@santiagoaguiar 

Checking in with you.
Please check out the new version of Raneto and see our "example" directory on the master branch for usage.

I'll close this in ~1 week unless I hear back.

**Comment by santiagoaguiar** [comment]
Thanks a lot! It worked perfectly, it was exactly what we needed. We are now just hosting content, public and themes in our repo.

**Comment by ryanlelek** [comment]
Wonderful! Glad it's working for you.
Thanks for the suggestion and let us know how else we can be helpful.
