### ISSUE TITLE
This Raneto doesn't support online creating pages, right?

### ISSUE THREAD

**Issue by luxuryzhou** [gilbitron/Raneto#57]
## does it support online creating pages or not?

and another issue is that how to add Chinese searching support?

above two.

thank u.

**Comment by vyp** [comment]
@luxuryzhou No I do not believe it does support creating pages from the website itself, at least in its current form.

For Chinese searching, you will probably have to modify raneto to add support for lunr-languages: https://github.com/olivernn/lunr.js/issues/91#issuecomment-47707106. But as you can see in that link, lunr-languages does not yet support Chinese.

Another potential option would be to try and replace the lunr that Raneto uses with https://github.com/codepiano/lunr.js, which seems like a Chinese version of lunr.js (found with the comment just below the previously linked comment). I haven't used this though, so I'm not sure if this only support Chinese, or supports both English and Chinese.

**Comment by codepiano** [comment]
My fork of lunr supports both English and Chinese.I use it to replace the original lunr repo in gitbook dependency, and it works well.

**Comment by vyp** [comment]
@codepiano That's pretty cool! Thanks for clarifying. :+1:

**Comment by codepiano** [comment]
@vyp I'll test whether it wokrs well in Raneto when I have time. Raneto is a nice tool.

**Comment by ryanlelek** [comment]
@luxuryzhou, online editing of pages was contributed by GitHub user "matthiassb" and was released yesterday in v0.7.0. I made small enhancements in v0.7.1, so you should be good to go there.

@codepiano, @vyp, moving the Chinese search/localization to similar issue #41 and closing this issue.

**Comment by ZhangTongLe** [comment]
@codepiano It can support Chinese raneto, share with us, thank you!
Look forward to your reply, email: 1071235258@qq.com.
