### ISSUE TITLE
Image URLS

### ISSUE THREAD

**Issue by thedaftbadger** [gilbitron/Raneto#58]
I have left the standard config unchanged for the `image` location...
`image_url: '/images',`

I am running a windows server and Raneto is working perfectly but I just can't get embedded images to display. MD files display perfectly.

I have created an images folder in the root as I guess this is where the images should be?
![image folder](https://cloud.githubusercontent.com/assets/13657363/9605542/3b227d96-50b6-11e5-973f-44e44c6f9ca7.jpg)

Within this folder I have placed an image called `image.jpg`

If I create an image in an MD file like this....
`![Test](%image_url%/image.jpg)`

The image is not displayed. If I check the source html on the rendered web page I can see the url is ...
`<img alt="Test" src="/images/image.jpg">`

I can't figure out if this is wrong with the root image folder location or an issue with Raneto locating o them?

![screenshot_090115_023625_pm](https://cloud.githubusercontent.com/assets/13657363/9605648/da7fda28-50b6-11e5-967e-05c02e2d502f.jpg)

Help much appreciated on this one.

**Comment by mrvautin** [comment]
The images folder would likely need to be created within the public folder.

**Comment by thedaftbadger** [comment]
I tried that but still had the same issue with the image not being displayed. If I manually browse to the image using the web URL I get a 404 from Raneto.

**Comment by thedaftbadger** [comment]
Fixed. Reinstalled Node.js

**Comment by ryanlelek** [comment]
@thedaftbadger - Seems like you got it fixed? If you're having more issues, please reopen this issue or create a new one and I'll give it a look.
