### ISSUE TITLE
Prevent syntax highlighting

### ISSUE THREAD

**Issue by twnaing** [gilbitron/Raneto#62]
I am experiencing incorrect language detection by `highlight.js`. 

Is there any config to prevent `highlight.js` in Raneto?

In [highlight.js doc](https://highlightjs.org/usage/) they suggest to use `nohighlight` class on `code` element. However Raneto generate `lang-nohighlight` on `code` element.

If Raneto could use [Fenced code blocks of Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks) or something similar I think I could achieve this with 

```markdown
    ```nohighlight
   code here
    ```
```

![markdown-table](https://cloud.githubusercontent.com/assets/801973/10042095/3511f48a-620f-11e5-892e-1389dc9b4e2b.jpg)

![markdown-table-raneto](https://cloud.githubusercontent.com/assets/801973/10042155/9fee67de-620f-11e5-85c5-113cb2220a2d.jpg)

**Comment by ryanlelek** [comment]
@twnaing 

Curious, does pull request #59 fix your issue?
I'll make a release later tonight for you to test with, or just pull from master.

**Comment by twnaing** [comment]
Sorry for late reply, I will test tonight and reply ASAP.

**Comment by twnaing** [comment]
Yes latest master fixed my issue.
