### ISSUE TITLE
Demo showcase doesn't match current version (v0.7.1)

### ISSUE THREAD

**Issue by draptik** [gilbitron/Raneto#67]
Just a heads up that the current demo showcase at http://docs.raneto.com/ is not up-to-date.

Example:

http://docs.raneto.com/templates/customizing-the-template

still has:

```
All of the template views can be found in the views folder 
```

The source code for the demo page is already up-to-date (https://github.com/gilbitron/Raneto/blob/0.7.1/content/templates/customizing-the-template.md)

```
All of the template views can be found in the themes/default/
```

The demo showcase probably just has to be redeployed with the current content.

**Comment by ryanlelek** [comment]
Thanks @draptik. I'm not sure how this is dont currenty but will find out

@gilbitron is updating the documentation as simple as editing the gh-pages branch?

**Comment by gilbitron** [comment]
@ryanlelek No it's hosted on Heroku. I've just pushed the new version to the demo site. I needed to make some changes to `pakcage.json` to make it work.

**Comment by draptik** [comment]
Cool. Thanks for the quick fix @gilbitron !
