### ISSUE TITLE
Update Node version in README

### ISSUE THREAD

**Issue by gilbitron** [gilbitron/Raneto#71]
As per https://github.com/gilbitron/Raneto/commit/b15568971f030632478e73a38724f8e3051a3012#commitcomment-14078134

**Comment by ryanlelek** [comment]
I'm confused about this.
Is Node v4.x a requirement to function moving forward?
Or is this just a direction decision to not support anything below v4?

**Comment by vyp** [comment]
@ryanlelek Cannot answer the question, but Node 0.x is 'alpha/beta' anyway (according to semver), so not supporting anything below v4 is acceptable in my opinion. (NB: as you probably already know, it's technically "v4", but it's really just "v1", so everything below v4 is 0.x)

**Comment by ryanlelek** [comment]
Ok, >= v4.x seems fine.
Worst-case scenario is a "WARN" in NPM for those legacy users
