### ISSUE TITLE
Raneto will not install

### ISSUE THREAD

**Issue by nashv** [gilbitron/Raneto#75]
PS C:\Users\nash> cd C:\Users\nash\Downloads\Raneto-0.7.1\Raneto-0.7.1
PS C:\Users\nash\Downloads\Raneto-0.7.1\Raneto-0.7.1> npm install
npm WARN engine raneto-core@0.2.0: wanted: {"node":"~0.10.0"} (current: {"node":"4.0.0","npm":"2.14.2"})
\
> raneto@0.7.1 postinstall C:\Users\nash\Downloads\Raneto-0.7.1\Raneto-0.7.1
> npm update && ./node_modules/.bin/bower install

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! raneto@0.7.1 postinstall: `npm update && ./node_modules/.bin/bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raneto@0.7.1 postinstall script 'npm update && ./node_modules/.bin/bower install'.
npm ERR! This is most likely a problem with the raneto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm update && ./node_modules/.bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls raneto
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nash\Downloads\Raneto-0.7.1\Raneto-0.7.1\npm-debug.log
PS C:\Users\nash\Downloads\Raneto-0.7.1\Raneto-0.7.1>
[npm-debug.log.txt](https://github.com/gilbitron/Raneto/files/40732/npm-debug.log.txt)

**Comment by ryanlelek** [comment]
Hi nashv,

Sorry for the trouble.
I'm using a Windows 7 box now to diagnose and fix.
Will respond shortly

**Comment by ryanlelek** [comment]
Ok, I think I've found a fix or at least something to move us along.
Please git clone the master branch and try `npm install` again.
If all goes well, follow that with `npm start`

Ryan

**Comment by nashv** [comment]
Great now it installs, but won't start

PS C:\Users\nash> cd .\Technical\Raneto\
PS C:\Users\nash\Technical\Raneto> ls


    Directory: C:\Users\nash\Technical\Raneto


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        21-Nov-15     19:40                app
d-----        21-Nov-15     19:40                content
d-----        21-Nov-15     19:40                example
d-----        21-Nov-15     19:40                public
d-----        21-Nov-15     19:40                themes
-a----        21-Nov-15     19:40            501 .gitignore
-a----        21-Nov-15     19:40            480 .jshintrc
-a----        21-Nov-15     19:40            495 gulpfile.js
-a----        21-Nov-15     19:40           2626 HISTORY.md
-a----        21-Nov-15     19:40           1103 LICENSE
-a----        21-Nov-15     19:40           1603 package.json
-a----        21-Nov-15     19:40           1466 README.md


PS C:\Users\nash\Technical\Raneto> npm install
npm WARN engine raneto-core@0.2.0: wanted: {"node":"~0.10.0"} (current: {"node":"4.0.0","npm":"2.14.2"})
|
> raneto@0.7.1 postinstall C:\Users\nash\Technical\Raneto
> npm update && npm run gulp


> raneto@0.7.1 gulp C:\Users\nash\Technical\Raneto
> gulp

[19:49:34] Using gulpfile ~\Technical\Raneto\gulpfile.js
[19:49:34] Starting 'copy_libs'...
[19:49:38] Finished 'copy_libs' after 3.13 s
[19:49:38] Starting 'default'...
[19:49:38] Finished 'default' after 26 μs
basic-auth-connect@1.0.0 node_modules\basic-auth-connect

extend@3.0.0 node_modules\extend

fitvids@1.0.2 node_modules\fitvids

cookie-parser@1.4.0 node_modules\cookie-parser
├── cookie-signature@1.0.6
└── cookie@0.2.2

serve-favicon@2.3.0 node_modules\serve-favicon
├── fresh@0.3.0
├── ms@0.7.1
├── etag@1.7.0
└── parseurl@1.3.0

underscore@1.8.3 node_modules\underscore

debug@2.2.0 node_modules\debug
└── ms@0.7.1

marked@0.3.5 node_modules\marked

validator@4.1.0 node_modules\validator

morgan@1.6.1 node_modules\morgan
├── on-headers@1.0.1
├── basic-auth@1.0.3
├── depd@1.0.1
└── on-finished@2.3.0 (ee-first@1.1.1)

underscore.string@3.2.2 node_modules\underscore.string

raneto-core@0.2.0 node_modules\raneto-core
├── underscore.string@2.4.0
├── validator@3.43.0
└── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)

body-parser@1.14.1 node_modules\body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.1.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── raw-body@2.1.4 (unpipe@1.0.0)
├── qs@5.1.0
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── iconv-lite@0.4.12

express@4.13.3 node_modules\express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.3
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── qs@4.0.0
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)

supertest@1.1.0 node_modules\supertest
├── methods@1.1.1
└── superagent@1.3.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, mime@1.3.4, qs@2.3.3, readable-stream@1.0.27-1, formidable@1.0.14, form-data@0.2.0)

masonry-layout@3.3.2 node_modules\masonry-layout
├── get-size@1.2.2 (desandro-get-style-property@1.0.4)
├── fizzy-ui-utils@1.0.1 (desandro-matches-selector@1.0.3, doc-ready@1.0.3)
└── outlayer@1.4.2 (desandro-get-style-property@1.0.4, eventie@1.0.6, desandro-matches-selector@1.0.3, doc-ready@1.0.3, wolfy87-eventemitter@4.3.0)

gulp@3.9.0 node_modules\gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── minimist@1.2.0
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, fancy-log@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
└── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

mocha@2.3.3 node_modules\mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

highlightjs@8.7.0 node_modules\highlightjs

jquery@2.1.4 node_modules\jquery

bootstrap@3.3.5 node_modules\bootstrap

hogan-express@0.5.2 node_modules\hogan-express
└── hogan.js@3.0.2 (mkdirp@0.3.0, nopt@1.0.10)

lunr@0.5.12 node_modules\lunr

moment@2.10.6 node_modules\moment

gulp-shell@0.5.0 node_modules\gulp-shell
├── async@1.4.2
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
├── gulp-util@3.0.7 (object-assign@3.0.0, array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, chalk@1.1.1, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.12)
└── lodash@3.10.1

jshint@2.8.0 node_modules\jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0
PS C:\Users\nash\Technical\Raneto> npm start

> raneto@0.7.1 start C:\Users\nash\Technical\Raneto
> DEBUG=raneto node example/server.js

'DEBUG' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! raneto@0.7.1 start: `DEBUG=raneto node example/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raneto@0.7.1 start script 'DEBUG=raneto node example/server.js'.
npm ERR! This is most likely a problem with the raneto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=raneto node example/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls raneto
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nash\Technical\Raneto\npm-debug.log
[npm-debug.log.txt](https://github.com/gilbitron/Raneto/files/40907/npm-debug.log.txt)

**Comment by ryanlelek** [comment]
Ok, good news then.
It did break on start, but not in the place I expected.

Pull down master one more time and instead of `npm start` run `npm start_win`

**Comment by nashv** [comment]
Tried that, but won't work because it doesn't find start_win. (I did pull the master again)

PS C:\Users\nash\Technical\Raneto> npm start_win

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\nash\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.14.2 C:\Program Files\nodejs\node_modules\npm
PS C:\Users\nash\Technical\Raneto>

**Comment by ryanlelek** [comment]
Sorry, my lack of clarity.
With these custom and non-standard scripts, you'll need to invoke it like so:
`npm run start_win`

**Comment by nashv** [comment]
All right , it works now. Thank you very much for your prompt feedback.

**Comment by eijoac** [comment]
i follow the above steps and it can now start. However, i cannot see the default config.js file. I copied my old config.js file to the directory and configured it to point to my own content file, but it didn't work.

**Comment by eijoac** [comment]
found the config.default.js. the Doc on the website need to be updated.

**Comment by eijoac** [comment]
is the old ,/bin directory still needed? Are there any changes for the Heroku deployment procedures? Following the steps in the doc, my Heroku deployment stopped working. Thanks.

**Comment by ryanlelek** [comment]
Ok, I'll make a new issue to update the docs for config and ./bin

./bin is no longer necessary.
Here's a new Procfile to solve your Heroku deployment.
However, since it looks like we're moving Raneto to be a module on NPM, it might be better to make a new project that is structured like the "example" directory and move your content folder over.

```
web: node example/server.js
```

**Comment by dcustodio** [comment]
Is the "npm run start_win" a temporary fix? I'm asking this because I run Raneto on Azure and it runs node apps with "npm start". Being a windows machine means that probably it won't run anymore. Any advice on this?
