### ISSUE TITLE
Changing the title and description meta tags in home page

### ISSUE THREAD

**Issue by castofclowns** [gilbitron/Raneto#78]
I just wanted to ask, how to change the title and descriptions meta tags in home page.

**Comment by ryanlelek** [comment]
By default, titles are drawn from the filename itself.
You may override this as well as meta in the document itself using the below instructions:
http://docs.raneto.com/usage/creating-pages

**Comment by castofclowns** [comment]
Thanks for the reply ryanlelek. 
By the way, I already apply a titles and descriptions tags to all pages.md. Except from the home page because what I want to use is still the default of the home page and the only thing I know where to apply the title in the home page is in the config.js the site_title which also reflect to other pages.

But what I want to happen is to put a separate title and description tag to the home page default without affecting the other pages. 

Also can you explain in details because I a new to this one.

Thanks...

**Comment by castofclowns** [comment]
anyone pls...

**Comment by ryanlelek** [comment]
Hi @castofclowns,

I've added a fix for you.
What we needed to do is add a "meta" object for the home page that contained the title and description.

Review the `config.default.js` file in the `example/` directory for details.
Be sure to use the latest copy of Raneto on the master branch in the meantime while we publish to NPM
