### ISSUE TITLE
vagrant container

### ISSUE THREAD

**Issue by draptik** [gilbitron/Raneto#79]
here is a simple vagrant container for Raneto:

https://github.com/draptik/vagrant-raneto

Have fun!

**Comment by ryanlelek** [comment]
Thanks for sharing, I'll check it out!

**Comment by ryanlelek** [comment]
@draptik, I'd like to close this issue, so what would you like to happen so your contribution can be seen?

Here are some options:
- merge a PR with your Vagrantfile changes
- add your respository to the "related projects" section

**Comment by draptik** [comment]
@ryanlelek I created a pull request (https://github.com/gilbitron/Raneto/pull/87) so you can close the issue.
