### ISSUE TITLE
Raneto allows creation of files outside its content directory

### ISSUE THREAD

**Issue by Radiergummi** [gilbitron/Raneto#86]
Using page names like `../../../testFile`, you can create files in any directory on the file system. As `.md` is attached this is not ultimately worse, though I think path characters should be escaped to avoid problems like this.

**Comment by ryanlelek** [comment]
Agreed, very big security hole.

Do you feel this you be sufficient?
Only issue I see is it removes all directory paths.
Can either patch the module or rework Raneto to work around this

https://github.com/parshap/node-sanitize-filename

**Comment by Radiergummi** [comment]
I thought about `filename = filename.replace(/\//g, '-')`, that might be enough already, `sanitize-filename` looks good too though...

**Comment by ryanlelek** [comment]
It seems like both the module and the code would remove any subdirectories.
And I don't see an obvious easy way around it

Subdirectories are key to the structure and organization of articles, so I'm stumped.

**Comment by Radiergummi** [comment]
Well, looking at the [add page route](https://github.com/gilbitron/Raneto/blob/master/app/index.js#L144), we could do it like so:  

````javascript
  app.post('/rn-add-page', function (req, res, next) {

  // replace slashes in filename
  filename = req.body.name.replace(/\//g, '-');

  var filePath = path.normalize(raneto.config.content_dir + (! ! req.body.category ? req.body.category + '/' : '') + filename + '.md');

  fs.open(filePath, 'a', function (err, fd) {
    fs.close(fd);
    if (err) {
      console.log(err);
      return res.json({
        status  : 1,
        message : err
      });
    }
    res.json({
      status  : 0,
      message : 'Page Created'
    });
  });
});
````

As far as I've seen, there are no secondary level categories, so this would not break the subdirectory functionality, or am I missing something?
