### ISSUE TITLE
Images embedded in documents are not displayed

### ISSUE THREAD

**Issue by helenamunoz** [gilbitron/Raneto#88]
In commit #c98e24c8f6f5224e1729284d6a3fc5acba6a14e3, the request handler regex was changed from "app.get(*)/" to "app.get(/^([^.]*)/", and the line res.sendfile(filePath); was removed from the handler. As a result, image files are not served anymore.

**Comment by ryanlelek** [comment]
Good point, this is a problem that needs a long term solution.
In the short-term, you could utilize external hosting services for the images to get back up and running quickly.

Moving forward, we'll likely have a separate handler for content-related images.

If you have theme-related images, I'd recommend putting them in themes/default/images until we can extract the themes into separate packages
